name: Go build and test

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go 1.20
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build and Test
      run: |
        go build -v ./...
        go test -v ./...
